---
all:
  hosts:
    # Pi NUT - primary
    pi-nut.mmoffice.net:
      ansible_user: pi

    # NAS01
    nas01.mmoffice.net:
      ansible_user: jgeerling

    # Pi NVR
    pi-nvr.mmoffice.net:
      ansible_user: pi

  children:
    primary:
      hosts:
        pi-nut.mmoffice.net:
    clients:
      hosts:
        nas01.mmoffice.net:
        pi-nvr.mmoffice.net:
